### ISSUE TITLE
app_launcher.bat assumes no venv

### ISSUE THREAD

**Issue by Cfomodz** [LukeWang01/Program-Trading-Based-on-Webull#16]
I don't know if people will be best served by having it in the documentation that you can just edit it with the path to your venv .exe or if people know that without it being said 🤷‍♂️ (if this is the case feel free to close unchanged :)

**Comment by LukeWang01** [comment]
please feel free to make changes.

**Comment by LukeWang01** [comment]
This repo is not supported, I moved to MooMoo.
