### ISSUE TITLE
Access token expiration

### ISSUE THREAD

**Issue by Cfomodz** [LukeWang01/Program-Trading-Based-on-Webull#18]
The readme states, "The access_token will expire weekly for your account security, you need to re-login to set up a new one." however I am unsure if this is a statement of fact or a statement of opinion.

Do you _want_ to let it expire in the name of security or are you saying Webull makes it that way and you are explaining the inconvenience?

If the latter, I can PR a quick refresh util.

**Comment by LukeWang01** [comment]
it's a fact, I tried to auto refresh the token, but it didn't work. Please PR if you can fix. Thank you.

**Comment by LukeWang01** [comment]
This repo is not supported, I moved to MooMoo.
